name: Update Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
+       with:
+         # allow pushes with GITHUB_TOKEN
+         persist-credentials: true

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: SEK-11
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: 'output/github-contribution-grid-snake.svg'

-     - name: Commit and push changes
-       uses: stefanzweifel/git-auto-commit-action@v4
-       with:
-         branch: main
-         commit_message: 'chore: update contribution snake'
-         file_pattern: 'output/github-contribution-grid-snake.svg'
+     - name: Commit and push SVG
+       run: |
+         git config user.name "github-actions[bot]"
+         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+         git add output/github-contribution-grid-snake.svg
+         git commit -m "chore: update contribution snake" || echo "No changes to commit"
+         git push
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
