name: Update Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: SEK-11
          output_file_name: 'output/github-contribution-grid-snake.svg'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'chore: update contribution snake'
          file_pattern: 'output/github-contribution-grid-snake.svg'
