name: 🐍 Generate Contribution Snake

# Run daily at UTC midnight, or manually via “Run workflow”
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: SEK-11
          output_file_name: github-contribution-grid-snake.svg

      - name: Commit & push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "chore: update contribution snake" || echo "no changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
