name: Update Contribution Snake

on:
  # runs daily at midnight UTC; also on any push to main
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Generate the snake SVG
      - name: Generate contribution snake
        uses: platane/gh-contributions-snake-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # outputs to output/github-contribution-grid-snake.svg
          output: './output/github-contribution-grid-snake.svg'

      # 3. Commit & push only that SVG file back to main
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: chore: update contribution snake
          file_pattern: output/github-contribution-grid-snake.svg
